start_x: 0.0288
start_y: 0.0580
end_x: 0.025
end_y: 0.10
theta_goal: 0

# Method
method: 2

# Visual servoing parameters
Tolerance: 0.5

# Plot trajectory (Form: Pixel_coordinates = a_* Cartesian + b_)
a_x: 3658.868971
b_x: 493
a_y: -3468.089952
b_y: 591.621936

# Motor values to finger angles
a_left: 0.002192
b_left: 1.027071
a_right: 0.002203
b_right: 0.325983

hold_left: 0.40
hold_right: 0.53

# Topics To be recorded
topics: {
  topic2: "aruco_simple/result",
  topic3: "object_position",
  topic4: "Motor_value"
}
