start_x: 0.0288
start_y: 0.0580
end_x: 0.025
end_y: 0.10

# Method
motion_planner: 1
visual_servoing: 1

# Visual servo Controller gain
Kp: 0.03

# Plot trajectory (Form: Pixel_coordinates = a_* Cartesian + b_)
a_x: 2938.4269
b_x: 603
a_y: -2721.6781
b_y: 560

# Motor values to finger angles
a_left: -0.002463
b_left: 1.04474
a_right: 0.002273
b_right: 0.561364

hold_left: 0.80
hold_right: 0.70
