start_x: 0.0288
start_y: 0.0580
end_x: 0.025
end_y: 0.10

# Method
motion_planner: 1
visual_servoing: 1

# Visual servo Controller gain
Kp: 0.03

# Plot trajectory (Form: Pixel_coordinates = a_* Cartesian + b_)
a_x: 2852.4236
b_x: 600.852678
a_y: -2929.1006
b_y: 429.60196

# Motor values to finger angles
a_left: 0.002192
b_left: 1.027071
a_right: 0.002203
b_right: 0.325983

hold_left: 0.80
hold_right: 0.70
