start_x: 0.0288
start_y: 0.0580
end_x: 0.025
end_y: 0.10

# Visual servo Controller gain
Kp: 0.03

# Plot trajectory (Form: Pixel_coordinates = a_* Cartesian + b_)
a_x: 2938.4269
b_x: 603
a_y: -2721.6781
b_y: 560

# Motor values to finger angles
a_left: -0.002844
b_left: 1.0542
a_right: 0.002535
b_right: 0.55672
